// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albums.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAlbums = `-- name: CountAlbums :one
SELECT COUNT(*) FROM albums alb
WHERE (alb.artist_id = $1 OR $1 = '')
`

func (q *Queries) CountAlbums(ctx context.Context, artistID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAlbums, artistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (
    id, name, description, cover_url, artist_id, release_date
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, description, cover_url, artist_id, release_date, created_at
`

type CreateAlbumParams struct {
	ID          string
	Name        string
	Description pgtype.Text
	CoverUrl    pgtype.Text
	ArtistID    string
	ReleaseDate pgtype.Date
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CoverUrl,
		arg.ArtistID,
		arg.ReleaseDate,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverUrl,
		&i.ArtistID,
		&i.ReleaseDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlbumByID = `-- name: DeleteAlbumByID :exec
DELETE FROM albums
WHERE id = $1
`

func (q *Queries) DeleteAlbumByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAlbumByID, id)
	return err
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, name, description, cover_url, artist_id, release_date, created_at FROM albums
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAlbumByID(ctx context.Context, id string) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByID, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverUrl,
		&i.ArtistID,
		&i.ReleaseDate,
		&i.CreatedAt,
	)
	return i, err
}

const getAlbums = `-- name: GetAlbums :many
SELECT alb.id, alb.name, alb.description, alb.cover_url, alb.artist_id, alb.release_date, alb.created_at FROM albums alb
WHERE (alb.artist_id = $1 OR $1 = '')
ORDER BY alb.release_date DESC
LIMIT $2 OFFSET $3
`

type GetAlbumsParams struct {
	ArtistID string
	Limit    int32
	Offset   int32
}

func (q *Queries) GetAlbums(ctx context.Context, arg GetAlbumsParams) ([]Album, error) {
	rows, err := q.db.Query(ctx, getAlbums, arg.ArtistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CoverUrl,
			&i.ArtistID,
			&i.ReleaseDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbumByID = `-- name: UpdateAlbumByID :exec
UPDATE albums
SET
    name = COALESCE(NULLIF($1, ''), name),
    description = COALESCE(NULLIF($2, ''), description),
    cover_url = COALESCE(NULLIF($3, ''), cover_url),
    artist_id = COALESCE(NULLIF($4, ''), artist_id),
    release_date = COALESCE($5, release_date)
WHERE id = $6
`

type UpdateAlbumByIDParams struct {
	Name        interface{}
	Description interface{}
	CoverUrl    interface{}
	ArtistID    interface{}
	ReleaseDate pgtype.Date
	ID          string
}

func (q *Queries) UpdateAlbumByID(ctx context.Context, arg UpdateAlbumByIDParams) error {
	_, err := q.db.Exec(ctx, updateAlbumByID,
		arg.Name,
		arg.Description,
		arg.CoverUrl,
		arg.ArtistID,
		arg.ReleaseDate,
		arg.ID,
	)
	return err
}
