// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArtists = `-- name: CountArtists :one
SELECT COUNT(*) FROM artists
`

func (q *Queries) CountArtists(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArtists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (
	id, name, bio, cover_url
) VALUES (
	$1, $2, $3, $4
)
RETURNING id, name, bio, cover_url
`

type CreateArtistParams struct {
	ID       string
	Name     string
	Bio      pgtype.Text
	CoverUrl pgtype.Text
}

type CreateArtistRow struct {
	ID       string
	Name     string
	Bio      pgtype.Text
	CoverUrl pgtype.Text
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (CreateArtistRow, error) {
	row := q.db.QueryRow(ctx, createArtist,
		arg.ID,
		arg.Name,
		arg.Bio,
		arg.CoverUrl,
	)
	var i CreateArtistRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CoverUrl,
	)
	return i, err
}

const deleteArtistByID = `-- name: DeleteArtistByID :one
DELETE FROM artists
WHERE id = $1
RETURNING id, name, bio, cover_url, created_at
`

func (q *Queries) DeleteArtistByID(ctx context.Context, id string) (Artist, error) {
	row := q.db.QueryRow(ctx, deleteArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CoverUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, name, bio, cover_url, created_at FROM artists
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArtistByID(ctx context.Context, id string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CoverUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getArtists = `-- name: GetArtists :many
SELECT id, name, bio, cover_url, created_at FROM artists
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type GetArtistsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetArtists(ctx context.Context, arg GetArtistsParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getArtists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.CoverUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtistByID = `-- name: UpdateArtistByID :one
UPDATE artists
SET 
	name = COALESCE(NULLIF($1, ''), name),
	bio = COALESCE(NULLIF($2, ''), bio),
	cover_url = COALESCE(NULLIF($3, ''), cover_url)
WHERE id = $4
RETURNING id, name, bio, cover_url, created_at
`

type UpdateArtistByIDParams struct {
	Name     interface{}
	Bio      interface{}
	CoverUrl interface{}
	ID       string
}

func (q *Queries) UpdateArtistByID(ctx context.Context, arg UpdateArtistByIDParams) (Artist, error) {
	row := q.db.QueryRow(ctx, updateArtistByID,
		arg.Name,
		arg.Bio,
		arg.CoverUrl,
		arg.ID,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CoverUrl,
		&i.CreatedAt,
	)
	return i, err
}
