// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package repository

import (
	"context"
)

const followArtist = `-- name: FollowArtist :exec
INSERT INTO follows (follower_id, artist_id)
VALUES ($1, $2)
`

type FollowArtistParams struct {
	FollowerID string
	ArtistID   string
}

func (q *Queries) FollowArtist(ctx context.Context, arg FollowArtistParams) error {
	_, err := q.db.Exec(ctx, followArtist, arg.FollowerID, arg.ArtistID)
	return err
}

const getFollowersByArtistID = `-- name: GetFollowersByArtistID :many
SELECT follower_id FROM follows
WHERE artist_id = $1
`

func (q *Queries) GetFollowersByArtistID(ctx context.Context, artistID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getFollowersByArtistID, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var follower_id string
		if err := rows.Scan(&follower_id); err != nil {
			return nil, err
		}
		items = append(items, follower_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowArtist = `-- name: UnfollowArtist :exec
DELETE FROM follows
WHERE follower_id = $1 AND artist_id = $2
`

type UnfollowArtistParams struct {
	FollowerID string
	ArtistID   string
}

func (q *Queries) UnfollowArtist(ctx context.Context, arg UnfollowArtistParams) error {
	_, err := q.db.Exec(ctx, unfollowArtist, arg.FollowerID, arg.ArtistID)
	return err
}
