// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: genres.sql

package repository

import (
	"context"
)

const countGenres = `-- name: CountGenres :one
SELECT COUNT(*) from genres
`

func (q *Queries) CountGenres(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGenres)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGenre = `-- name: CreateGenre :one
INSERT INTO genres (
	id, name
) VALUES (
	$1, $2
)
RETURNING id, name
`

type CreateGenreParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateGenre(ctx context.Context, arg CreateGenreParams) (Genre, error) {
	row := q.db.QueryRow(ctx, createGenre, arg.ID, arg.Name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteGenreByID = `-- name: DeleteGenreByID :one
DELETE FROM genres
WHERE id = $1
RETURNING id, name
`

func (q *Queries) DeleteGenreByID(ctx context.Context, id string) (Genre, error) {
	row := q.db.QueryRow(ctx, deleteGenreByID, id)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getGenreByID = `-- name: GetGenreByID :one
SELECT id, name FROM genres
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGenreByID(ctx context.Context, id string) (Genre, error) {
	row := q.db.QueryRow(ctx, getGenreByID, id)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getGenres = `-- name: GetGenres :many
SELECT id, name FROM genres
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type GetGenresParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetGenres(ctx context.Context, arg GetGenresParams) ([]Genre, error) {
	rows, err := q.db.Query(ctx, getGenres, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGenreByID = `-- name: UpdateGenreByID :one
UPDATE genres
SET name = COALESCE(NULLIF($1, ''), name)
WHERE id = $2
RETURNING id, name
`

type UpdateGenreByIDParams struct {
	Name interface{}
	ID   string
}

func (q *Queries) UpdateGenreByID(ctx context.Context, arg UpdateGenreByIDParams) (Genre, error) {
	row := q.db.QueryRow(ctx, updateGenreByID, arg.Name, arg.ID)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
