// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID          string
	Name        string
	Description pgtype.Text
	CoverUrl    pgtype.Text
	ArtistID    string
	ReleaseDate pgtype.Date
	CreatedAt   pgtype.Timestamptz
}

type Artist struct {
	ID        string
	Name      string
	Bio       pgtype.Text
	CoverUrl  pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Genre struct {
	ID   string
	Name string
}

type Playlist struct {
	ID          string
	Name        string
	Description pgtype.Text
	UserID      string
	CreatedAt   pgtype.Timestamptz
}

type PlaylistSong struct {
	PlaylistID string
	SongID     string
	AddedAt    pgtype.Timestamptz
}

type Song struct {
	ID              string
	Name            string
	DurationSeconds float64
	AudioUrl        string
	AlbumID         string
	GenreID         pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type User struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	Role         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}
