// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package repository

import (
	"context"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (id, user_id, title, message)
VALUES ($1, $2, $3, $4)
`

type CreateNotificationParams struct {
	ID      string
	UserID  string
	Title   string
	Message string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Message,
	)
	return err
}

const getNotificationsByUserID = `-- name: GetNotificationsByUserID :many
SELECT id, user_id, title, message, is_read, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetNotificationsByUserID(ctx context.Context, userID string) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE id = $1
`

func (q *Queries) MarkAsRead(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markAsRead, id)
	return err
}
