// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlists.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSongToPlaylist = `-- name: AddSongToPlaylist :exec
INSERT INTO playlist_songs (
	playlist_id, song_id
) VALUES (
	$1, $2
) ON CONFLICT (playlist_id, song_id) DO NOTHING
`

type AddSongToPlaylistParams struct {
	PlaylistID string
	SongID     string
}

func (q *Queries) AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) error {
	_, err := q.db.Exec(ctx, addSongToPlaylist, arg.PlaylistID, arg.SongID)
	return err
}

const clearPlaylist = `-- name: ClearPlaylist :exec
DELETE FROM playlist_songs
WHERE playlist_id = $1
`

func (q *Queries) ClearPlaylist(ctx context.Context, playlistID string) error {
	_, err := q.db.Exec(ctx, clearPlaylist, playlistID)
	return err
}

const countPlaylistsByUser = `-- name: CountPlaylistsByUser :one
SELECT COUNT(*) FROM playlists
WHERE user_id = $1
`

func (q *Queries) CountPlaylistsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPlaylistsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSongsInPlaylist = `-- name: CountSongsInPlaylist :one
SELECT COUNT(*) FROM playlist_songs
WHERE playlist_id = $1
`

func (q *Queries) CountSongsInPlaylist(ctx context.Context, playlistID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSongsInPlaylist, playlistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (
	id, name, description, user_id
) VALUES (
	$1, $2, $3, $4
)
RETURNING id, name, description, user_id, created_at
`

type CreatePlaylistParams struct {
	ID          string
	Name        string
	Description pgtype.Text
	UserID      string
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, createPlaylist,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UserID,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlaylistByID = `-- name: DeletePlaylistByID :one
DELETE FROM playlists
WHERE id = $1
RETURNING id, name, description, user_id, created_at
`

func (q *Queries) DeletePlaylistByID(ctx context.Context, id string) (Playlist, error) {
	row := q.db.QueryRow(ctx, deletePlaylistByID, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getPlaylistByID = `-- name: GetPlaylistByID :one
SELECT id, name, description, user_id, created_at FROM playlists
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlaylistByID(ctx context.Context, id string) (Playlist, error) {
	row := q.db.QueryRow(ctx, getPlaylistByID, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getPlaylistsByUser = `-- name: GetPlaylistsByUser :many
SELECT id, name, description, user_id, created_at FROM playlists
WHERE user_id = $1
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type GetPlaylistsByUserParams struct {
	UserID string
	Limit  int32
	Offset int32
}

func (q *Queries) GetPlaylistsByUser(ctx context.Context, arg GetPlaylistsByUserParams) ([]Playlist, error) {
	rows, err := q.db.Query(ctx, getPlaylistsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsByPlaylistID = `-- name: GetSongsByPlaylistID :many
SELECT s.id, s.name, s.duration_seconds, s.audio_url, s.album_id, s.genre_id, s.created_at FROM songs s
JOIN playlist_songs ps ON s.id = ps.song_id
WHERE ps.playlist_id = $1
ORDER BY ps.added_at DESC
`

func (q *Queries) GetSongsByPlaylistID(ctx context.Context, playlistID string) ([]Song, error) {
	rows, err := q.db.Query(ctx, getSongsByPlaylistID, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationSeconds,
			&i.AudioUrl,
			&i.AlbumID,
			&i.GenreID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSongFromPlaylist = `-- name: RemoveSongFromPlaylist :exec
DELETE FROM playlist_songs
WHERE playlist_id = $1 AND song_id = $2
`

type RemoveSongFromPlaylistParams struct {
	PlaylistID string
	SongID     string
}

func (q *Queries) RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) error {
	_, err := q.db.Exec(ctx, removeSongFromPlaylist, arg.PlaylistID, arg.SongID)
	return err
}
