// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: songs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSongs = `-- name: CountSongs :one
SELECT COUNT(*) FROM songs s
JOIN albums a ON s.album_id = a.id
WHERE (s.album_id = $1 OR $1 = '')
  AND (a.artist_id = $2 OR $2 = '')
  AND (s.genre_id = $3 OR $3 IS NULL)
`

type CountSongsParams struct {
	AlbumID  string
	ArtistID string
	GenreID  pgtype.Text
}

func (q *Queries) CountSongs(ctx context.Context, arg CountSongsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSongs, arg.AlbumID, arg.ArtistID, arg.GenreID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSong = `-- name: CreateSong :one
INSERT INTO songs (
  id, name, duration_seconds, audio_url, cover_url, album_id, genre_id
) VALUES (
	$1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, duration_seconds, audio_url, cover_url, album_id, genre_id, created_at
`

type CreateSongParams struct {
	ID              string
	Name            string
	DurationSeconds float64
	AudioUrl        string
	CoverUrl        pgtype.Text
	AlbumID         string
	GenreID         pgtype.Text
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, createSong,
		arg.ID,
		arg.Name,
		arg.DurationSeconds,
		arg.AudioUrl,
		arg.CoverUrl,
		arg.AlbumID,
		arg.GenreID,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationSeconds,
		&i.AudioUrl,
		&i.CoverUrl,
		&i.AlbumID,
		&i.GenreID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSongByID = `-- name: DeleteSongByID :exec
DELETE FROM songs
WHERE id = $1
`

func (q *Queries) DeleteSongByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSongByID, id)
	return err
}

const getSongByID = `-- name: GetSongByID :one
SELECT id, name, duration_seconds, audio_url, cover_url, album_id, genre_id, created_at FROM songs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSongByID(ctx context.Context, id string) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByID, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationSeconds,
		&i.AudioUrl,
		&i.CoverUrl,
		&i.AlbumID,
		&i.GenreID,
		&i.CreatedAt,
	)
	return i, err
}

const getSongs = `-- name: GetSongs :many
SELECT s.id, s.name, s.duration_seconds, s.audio_url, s.cover_url, s.album_id, s.genre_id, s.created_at FROM songs s
JOIN albums a ON s.album_id = a.id
WHERE (s.album_id = $1 OR $1 = '')
  AND (a.artist_id = $2 OR $2 = '')
  AND (s.genre_id = $3 OR $3 IS NULL)
ORDER BY s.created_at DESC
LIMIT $4 OFFSET $5
`

type GetSongsParams struct {
	AlbumID  string
	ArtistID string
	GenreID  pgtype.Text
	Limit    int32
	Offset   int32
}

func (q *Queries) GetSongs(ctx context.Context, arg GetSongsParams) ([]Song, error) {
	rows, err := q.db.Query(ctx, getSongs,
		arg.AlbumID,
		arg.ArtistID,
		arg.GenreID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationSeconds,
			&i.AudioUrl,
			&i.CoverUrl,
			&i.AlbumID,
			&i.GenreID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSongByID = `-- name: UpdateSongByID :exec
UPDATE songs
SET
  name = COALESCE(NULLIF($1, ''), name),
  duration_seconds = CASE WHEN $2 > 0 THEN $2 ELSE duration_seconds END,
  audio_url = COALESCE(NULLIF($3, ''), audio_url),
  cover_url = COALESCE(NULLIF($4, ''), cover_url),
  album_id = COALESCE(NULLIF($5, ''), album_id),
  genre_id = COALESCE(NULLIF($6, ''), genre_id)
WHERE id = $7
`

type UpdateSongByIDParams struct {
	Name            interface{}
	DurationSeconds interface{}
	AudioUrl        interface{}
	CoverUrl        interface{}
	AlbumID         interface{}
	GenreID         interface{}
	ID              string
}

func (q *Queries) UpdateSongByID(ctx context.Context, arg UpdateSongByIDParams) error {
	_, err := q.db.Exec(ctx, updateSongByID,
		arg.Name,
		arg.DurationSeconds,
		arg.AudioUrl,
		arg.CoverUrl,
		arg.AlbumID,
		arg.GenreID,
		arg.ID,
	)
	return err
}
