// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
	id, username, email, password_hash, role
) VALUES (
	$1, $2, $3, $4, COALESCE(NULLIF($5::varchar, ''), 'user')
)
RETURNING id, username, email, role, created_at
`

type CreateUserParams struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	Role         string
}

type CreateUserRow struct {
	ID        string
	Username  string
	Email     string
	Role      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, role, created_at, password_hash FROM users
WHERE email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID           string
	Username     string
	Email        string
	Role         pgtype.Text
	CreatedAt    pgtype.Timestamptz
	PasswordHash string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, role, created_at, password_hash FROM users
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID           string
	Username     string
	Email        string
	Role         pgtype.Text
	CreatedAt    pgtype.Timestamptz
	PasswordHash string
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, email, role, created_at FROM users
ORDER BY username ASC
LIMIT $1 OFFSET $2
`

type GetUsersParams struct {
	Limit  int32
	Offset int32
}

type GetUsersRow struct {
	ID        string
	Username  string
	Email     string
	Role      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2, email = $3, password_hash = $4, role = $5
WHERE id = $1
RETURNING id, username, email, role, created_at
`

type UpdateUserParams struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	Role         pgtype.Text
}

type UpdateUserRow struct {
	ID        string
	Username  string
	Email     string
	Role      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2
WHERE id = $1
RETURNING id, username, email, role, created_at
`

type UpdateUserRoleParams struct {
	ID   string
	Role pgtype.Text
}

type UpdateUserRoleRow struct {
	ID        string
	Username  string
	Email     string
	Role      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i UpdateUserRoleRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
